version: "3.9"
services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
  memcache:
    image: 'memcached:latest'
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64